name: flutter_edd
description: "A package that facilitates event-driven design for Flutter apps"
repository: https://github.com/reyhanlioglu/flutter_edd/tree/master
topics:
  - event
  - event-driven
  - event-driven-design
  - reactive-programming
  - bloc
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
